### ISSUE TITLE
Add PREFIX for dbpedia-nl

### ISSUE THREAD

**Issue by IanHopkinson** [scraperwiki/newsreader-api#11]
Should I define a dbpedia-nl prefix for my Simple API queries like?

dbpedia-nl = http://nl.dbpedia.org/resource/

this is relevant to the Dutch House of Representatives dataset. Marco says not required because the SPARQL endpoint has dbpedianl defined on it. However, I believe our policy has been to explicitly define the PREFIXes we are using.

**Comment by StevenMaude** [comment]
Whether you need to for the queries, I'm not sure, but I *think* you'd need to add it if you want it to be abbreviated in the results, probably [here](https://github.com/scraperwiki/newsreader-api/blob/master/app/queries/queries.py#L20-L42).
