### ISSUE TITLE
Page 1 is different from other pages

### ISSUE THREAD

**Issue by StevenMaude** [scraperwiki/newsreader-api#3]
https://bitbucket.org/scraperwikids/newsreader_api_flask_app/issue/123/page-1-is-different-from-other-pages

**Comment by IanHopkinson** [comment]
Actually, URLs of the form below are entirely valid:

https://newsreader.scraperwiki.com/wikinews/actors_of_a_type/page/2?uris.0=dbo%3ACompany

The redirection of /page/1 is a feature of Pagination, so we can't fix it:
 
http://flask.pocoo.org/snippets/44/

**Comment by IanHopkinson** [comment]
Fixed by a bit of documentation 18a77921c4cb74db6923ffc28038f930d7933d2d

**Comment by StevenMaude** [comment]
> The redirection of /page/1 is a feature of Pagination, so we can't fix it.

If we wanted to, we could!

That said, the `/page/1` URL still works regardless.
